name: deploy site
on: workflow_dispatch
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version-file: .java-version
          distribution: zulu
          cache: maven
      - name: Generate Site
        run: ./mvnw -e --batch-mode clean site -Dcheckstyle.skip=true -Djacoco.skip=true
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: target/site
          clean: true
